In [1]:
import pandas as pd

In [69]:
from datetime import datetime

In [3]:
csv = pd.read_csv("final.csv")

,Date,Location,Shape,Duration,Population,Count
33184,1/1/00,"Patoka, IL",triangle,5 minutes,584.0,1
36584,1/1/01,"Oceanside, CA",light,Minutes,167086.0,1
14673,1/1/02,"Philadelphia, PA",triangle,5 minutes,1526006.0,1
36628,1/1/03,"McAllen, TX",disk,5min.,129877.0,1
31908,1/1/04,"Kenai, AK",light,15 minutes,7100.0,1
24160,1/1/05,"Phoenix, AZ",triangle,10 Min.,1445632.0,1
38018,1/1/06,"San Antonio/Laredo (between), TX",triangle,1: 45 minutes,1327407.0,1
34075,1/1/07,"Riverside, NJ",light,2 minutes,NaN,1
32369,1/1/08,"Waco, TX",fireball,5 seconds,124805.0,1
38311,1/1/09,"Asheboro, NC",cigar,3-4 min.,25012.0,1
40921,1/1/10,"Bakersfield, CA",light,1 minute,347483.0,1
18112,1/1/44,"San Diego, CA",cigar,3 minutes,1307402.0,1
21390,1/1/50,"Mount Hope, WV",unknown,unknown,1414.0,1
14933,1/1/52,"Salt Lake City, UT",unknown,Unknown,186440.0,1
19762,1/1/54,"Lakeland, FL",disk,most of the night,97422.0,1
4292,1/1/56,"Weirton, WV",disk,10 seconds,19746.0,1
30073,1/1/61,"Kendallville, IN",circle,30 seconds,9862.0,1
616,1/1/62,"Key West, FL",sphere,3 to 5 minutes,24649.0,1
27440,1/1/65,"St. Ansgar, IA",fireball,20 seconds,1107.0,1
6625,1/1/66,"Flagstaff, AZ",disk,10 minutes,65870.0,1
40215,1/1/68,"Lawndale, CA",circle,1 minute,32769.0,1
13064,1/1/69,"Greensburg, PA",unknown,unknown,14892.0,1
41784,1/1/70,"Joplin, MO",unknown,30 min,50150.0,1
20948,1/1/72,"Huntsville, AL",unknown,2 minutes,180105.0,1
4157,1/1/73,"Chattanooga, TN",oval,30 sec.,167674.0,1
705,1/1/74,"Kent, WA",cigar,5:00 min,92411.0,1
42050,1/1/75,"Goree/Mineral Wells (between), TX",light,3-4 hours,203.0,1
40692,1/1/77,"Westminster, CA",disk,5 minutes,89701.0,1
24159,1/1/78,"June Lake, CA",disk,15 min,629.0,1
22509,1/1/79,"Orange, CA",disk,20 minutes,136416.0,1
...,...,...,...,...,...,...
35479,9/8/66,"Hundred, WV",oval,30 sec,299.0,1
16081,9/8/67,"Hermosa Beach, CA",cigar,1-2 minutes,19506.0,1
12800,9/8/73,"Lewisburg, PA",triangle,3min,5792.0,1
21606,9/8/80,"Brewerton, NY",changing,36,4029.0,1
1311,9/8/98,"Emory (5 Mi East of), TX",fireball,4 sec,1239.0,1
37309,9/8/99,"Alsea, OR",light,3-4 minutes,164.0,1
10053,9/9/00,"Gardiner, MT",light,2 minutes,875.0,1
39123,9/9/01,"San Diego, CA",unknown,few seconds,1307402.0,1
11271,9/9/02,"Huntsville, TX",other,seconds,38548.0,1
20022,9/9/03,"Sarasota, FL",fireball,8-10 min,51917.0,1
18745,9/9/04,"Natchez, MS",unknown,1:00,15792.0,1
22680,9/9/05,"Gold Canyon, AZ",unknown,one hour or so,10159.0,1
26611,9/9/06,"Sturgis, MI",light,2 hrs.,10994.0,1
30317,9/9/07,"Las Vegas, NV",other,30 sec,583756.0,1
35082,9/9/08,"Shelbyville, IL",triangle,7 seconds,4700.0,1
40589,9/9/09,"Birmingham, AL",other,15 minutes,212237.0,1
39117,9/9/52,"Philadelphia, PA",circle,3 minutes,1526006.0,1
15743,9/9/54,"Beaumont, TX",disk,5 MINUTES,118296.0,1
28030,9/9/56,"Norfolk, VA",cigar,1.5 minutes,242803.0,1
17086,9/9/68,"Santa Rosa, CA",circle,8 seconds,167815.0,1
19587,9/9/69,"Austin, TX",sphere,12-15 Minutes,790390.0,1
5068,9/9/75,"Vineland, NJ",disk,10 mins.,60724.0,1
39128,9/9/78,"Imperial Beach, CA",other,2 minutes,26324.0,1
12331,9/9/82,"Mount Kisco, NY",sphere,30 sec,10877.0,1
3519,9/9/94,"Chico, CA",fireball,5-7seconds,86187.0,1
2084,9/9/95,"St. Charles (1.5 mi north of, Randall Road), IL",chevron,5-10 minutes,32974.0,1
19110,9/9/96,"San Francisco, CA",oval,Seconds/1 hour,805235.0,1
5386,9/9/97,"Las Vegas, NV",formation,5 minutes,583756.0,1
1322,9/9/98,"Tomah, WI",cylinder,15seconds+,9093.0,1
19602,9/9/99,"Marathon, FL",disk,10minutes,8297.0,1

In [81]:
csv1 = csv[['sight_time','location', 'shape_x','duration', 'population']]

In [82]:
csv1.columns = ['Date', 'Location', 'Shape', 'Duration', 'Population']

In [83]:
csv1['Count'] = csv1.groupby('Date')['Date'].transform('count')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [84]:
csv1 = csv1.drop_duplicates(subset='Date',keep='last')

In [85]:
csv1['Count'].unique()

array([  1,   2,   3,   5,   4,   6,  11,  36,   7,  12,   8,   9,  10,
        21,  13,  18,  15,  14,  17,  16,  22,  26,  19,  24,  44,  39,
        27,  20,  42,  28,  31,  32,  33,  29,  23,  25,  56,  49,  38,
        35,  41,  83,  37,  57,  47,  30, 101,  74, 156,  55,  63, 169])

In [86]:
csv1

,Date,Location,Shape,Duration,Population,Count
2,12/8/94,"McCall, ID",fireball,10 seconds (?),2991.0,1
3,12/29/94,"Lakeview, MI",light,5 min.,1007.0,1
4,1/4/95,"Noxen, PA",unknown,5 min.,633.0,1
5,1/3/95,"Marysville, WA",triangle,2 min.,60020.0,1
7,12/31/94,"Fontana, CA",light,10 min.,196069.0,1
10,12/30/94,"Los Angeles, CA",light,2 min.,3792621.0,1
11,12/24/94,"Seattle, WA",light,20 sec.,608660.0,1
12,1/22/95,"Tonasket, WA",rectangle,10 min.,1032.0,1
13,1/17/95,"Anchorage, AK",light,15 min.,291826.0,1
14,1/26/95,"Concrete, WA",light,55 min.,705.0,1
16,2/2/95,"Denmark, WI",cone,75 min,2123.0,1
17,2/7/95,"Tacoma, WA",unknown,5-7 sec,198397.0,1
19,1/7/80,"Oklahoma City, OK",other,10 min.,579999.0,1
20,11/26/89,"Dallas, TX",triangle,10 min.,1197816.0,1
22,7/25/95,"Ocate, NM",light,2 min,NaN,1
23,10/31/95,"Tacoma, WA",light,2 min.,198397.0,1
24,11/8/95,"Pilot Rock, OR",light,1 hr.,1502.0,1
25,11/11/95,"Rock Island, WA",light,20 sec.,788.0,1
26,12/1/95,"Owosso, MI",light,5 sec.,15194.0,1
28,12/5/95,"North Bend, WA",chevron,4 min.,5731.0,1
29,12/7/95,"Oldsmar, FL",light,4 sec.,13591.0,1
32,2/18/96,"Gainesville, FL",diamond,5 min.,124354.0,1
34,2/26/96,"Fort Lauderdale, FL",diamond,2 hrs.,165521.0,1
36,3/23/96,"Salinas, CA",light,50 sec.,150441.0,1
37,6/9/96,"Banning, CA",light,35 min.,29603.0,1
38,6/12/96,"Seattle, WA",light,5 sec.,608660.0,1
41,6/24/96,"Aurora, CO",changed,1 hour,325078.0,1
43,6/28/96,"Walled Lake, MI",light,5-7 min,6999.0,1
45,2/8/96,"St. Joseph, MO",sphere,5 sec.,76780.0,1
50,5/27/96,"Amargosa Valley, NV",light,1hr,NaN,1
...,...,...,...,...,...,...
42812,7/24/10,"Lake Oswego, OR",triangle,2 minutes,36619.0,13
42817,8/20/10,"Shafter, CA",light,5 minutes,16988.0,8
42827,8/14/10,"Kennewick, WA",fireball,10 seconds,73917.0,20
42828,4/26/10,"Markle, IN",sphere,2 mins,1095.0,3
42829,8/17/10,"Oak Lawn, IL",light,4 minutes,56690.0,8
42833,8/22/10,"Morrisville, PA",circle,5 minutes,1265.0,9
42835,8/23/10,"Penn Hills, PA",light,4 min,NaN,8
42838,8/13/10,"Durango, CO",light,5 mins,16887.0,21
42847,8/6/10,"Cheyenne, WY",other,5 minutes,59466.0,13
42848,1/13/10,"Gulf Breeze, FL",unknown,4 minutes,5763.0,7
42850,8/21/10,"Franklin Square, NY",fireball,20 minutes,29320.0,11
42860,8/24/10,"Visalia, CA",triangle,10 minutes,124442.0,11
42862,12/31/09,"Slidell, LA",sphere,3 minutes,27068.0,17
42873,12/22/09,"Wellersburg, PA",light,30 sec.,181.0,2
42875,8/26/10,"Ruch, OR",light,1 Minute,840.0,12
42876,6/29/10,"Signal Mountain, TN",light,45 minutes to an hour,7554.0,7
42884,7/1/10,"Blue Springs, MO",light,15 seconds,52575.0,17
42886,4/1/09,"Columbia, MO",unknown,1 minute,108500.0,6
42890,4/1/05,"Wentzville, MO",chevron,1 minute,29070.0,7
42895,7/5/10,"Brooks, OR",sphere,5 min,398.0,16
42900,7/13/10,"Victor, ID",changing,5-10 minutes,1928.0,10
42903,8/3/08,"Bellingham, WA",cigar,not sure,80885.0,21
42909,8/25/10,"Atlantic City, NJ",light,20 minutes,39558.0,9
42911,8/21/90,"Phoenix, AZ",other,30 minutes,1445632.0,1
42912,8/30/10,"Wareham, MA",light,5 minutes,2896.0,2
42914,7/3/10,"Columbia, SC",formation,5 secs,129272.0,47
42915,7/15/98,"Bristol, RI",egg,4 min.,NaN,17
42918,8/28/10,"Rochester, NY",fireball,10 minutes,210565.0,19
42919,8/29/10,"Cokeville, WY",formation,3 minutes,535.0,9
42921,8/27/10,"Lincoln, IL",light,at least 1 second,14504.0,13

#

In [87]:
def lam(x):
    try:
        ret = datetime.strptime(x, '%Y-%m-%d')
    except:
        ret = datetime.strptime(x, '%m/%d/%y')
    return ret
csv1['Date'] = csv1['Date'].map(lam)

In [91]:
csv1 = csv1.sort_values('Date')

In [94]:
csv1 = csv1.head(6400)

In [95]:
csv1

,Date,Location,Shape,Duration,Population,Count
29363,1790-06-30,"Carlisle, NY",fireball,less than 1 minute,NaN,1
2896,1860-08-02,"Cherokee, NC",fireball,less than a minute?,2138.0,1
26973,1880-12-12,"Bellingham, WA",fireball,Unknown,80885.0,1
24184,1899-06-30,"Carrollton, MO",sphere,one hour,3784.0,1
13064,1969-01-01,"Greensburg, PA",unknown,unknown,14892.0,2
1868,1969-01-04,"Naples (just north of), FL",oval,???,19537.0,1
16185,1969-01-15,"Butte, MT",rectangle,unknown,NaN,3
16324,1969-01-19,"Butte, MT",other,unknown,NaN,2
6459,1969-01-20,"Lake Wales, FL",disk,5 minutes or so,14225.0,1
15571,1969-02-15,"Monroe, IN",sphere,15-20 seconds,842.0,1
21490,1969-03-01,"Perth Amboy, NJ",light,2 minutes,50814.0,2
40620,1969-03-15,"Oroville, WA",cross,2min,1686.0,1
37158,1969-04-01,"Loganville, GA",cigar,15 sec,10458.0,1
11747,1969-04-21,"Little Rock, AR",cylinder,12 minutes,193524.0,1
24288,1969-05-01,"Estill, SC",cigar,45 minutes,2040.0,5
31422,1969-05-15,"St. Louis, MO",cigar,2min,319294.0,2
33733,1969-06-01,"Barrington, IL",sphere,2 hours,10327.0,8
18153,1969-06-04,"Chance, MD",disk,5 MIN,353.0,1
16146,1969-06-05,"Windsor, SC",disk,30mint,121.0,1
32122,1969-06-10,"North Wildwood, NJ",triangle,3 minutes,4041.0,3
35261,1969-06-15,"Kent, WA",other,?,92411.0,5
22787,1969-06-21,"Ronkonkoma, NY",unknown,1 hour,19082.0,1
8312,1969-06-29,"Fort Lauderdale, FL",other,2-3 minutes,165521.0,1
39843,1969-06-30,"Detroit, MI",light,30 seconds,713777.0,4
27173,1969-07-01,"Payson, AZ",disk,&lt; 5 min.,15301.0,5
17997,1969-07-04,"Jacksonville Beach, FL",other,3 Minutes,21362.0,2
14745,1969-07-05,"Valdez, AK",disk,17 minutes,3976.0,1
33272,1969-07-07,"Miami, FL",light,hour,399457.0,3
24220,1969-07-10,"Chariton, IA",circle,5 min.,4321.0,2
32466,1969-07-15,"Geneseo (outside of), IL",unknown,10-20 minutes,6586.0,8
...,...,...,...,...,...,...
36249,2008-02-16,"Richmond, VA",changing,1 hr 16 mins,204214.0,9
33466,2008-02-17,"San Francisco, CA",light,60-90 seconds,805235.0,13
32444,2008-02-18,"Vaughn (Hwy 285; south of), NM",light,15 minutes,446.0,9
32371,2008-02-19,"Kalama, WA",disk,4 minutes,2344.0,16
39755,2008-02-20,"Puyallup, WA",chevron,6-8 min.,37022.0,25
32718,2008-02-21,"Converse, IN",light,30 min.off &amp; on,1265.0,15
34654,2008-02-22,"Cincinnati, OH",rectangle,3 mins,296943.0,8
39886,2008-02-23,"Crystal Lake, IL",fireball,30 seconds,40743.0,9
32566,2008-02-24,"Elizabeth, NJ",sphere,30 seconds,124969.0,7
35282,2008-02-25,"Port Saint Lucie, FL",flash,15 min.,164603.0,8
34451,2008-02-26,"Mastic, NY",rectangle,15 min,15481.0,8
37924,2008-02-27,"Lee Vining, CA",rectangle,One second,222.0,17
32666,2008-02-28,"Huntington, WV",disk,1.5-2minutes,49138.0,10
32760,2008-02-29,"Minneapolis (near; Hwy 81), KS",triangle,2 min.,2032.0,8
40773,2008-03-01,"Indianapolis, IN",disk,15 min,820445.0,10
40029,2008-03-02,"Salem, MO",light,25 minutes,4950.0,11
34711,2008-03-03,"Caney, KS",formation,5 minutes,2203.0,5
37115,2008-03-04,"Roper, NC",light,4 minutes,611.0,4
32791,2008-03-05,"Bowling Green, OH",oval,30 seconds,30028.0,9
32567,2008-03-06,"Murphy, OR",light,2 minutes,NaN,16
36344,2008-03-07,"Destin/Madison (between), FL",unknown,short,12305.0,6
36598,2008-03-08,"Breinigsville, PA",light,1 Second?,4138.0,12
33269,2008-03-09,"Casa Grande, AZ",light,10 minutes +,48571.0,12
33478,2008-03-10,"Goodlettsville, TN",unknown,5 min,15921.0,12
32586,2008-03-11,"Challis, ID",triangle,1 minute,1081.0,7
33617,2008-03-12,"Lake Elmo, MN",unknown,3-4 min,8069.0,4
34257,2008-03-13,"Paducah, KY",disk,1 min,25024.0,9
39065,2008-03-14,"Wichita, KS",cigar,30 secs,382368.0,7
40289,2008-03-15,"Fortuna, CA",sphere,5 Min,11926.0,14
37833,2008-03-16,"Deming, NM",light,7 seconds,14855.0,7

In [96]:
csv1.to_csv("data.csv")